### ISSUE TITLE
[Bug] Mana regeneration randomly stops upon changing dimensions or reloading world

### ISSUE THREAD

**Issue by Jackiecrazy** [iron431/Irons-Spells-n-Spellbooks#18] opened 2023-05-03 11:39 UTC
### Observed behaviour

Mana will randomly fail to regenerate. This seems to be most obvious after dimension change or reload.

### Expected behaviour

Mana should regenerate regardless of reload or dimension.

### Steps to reproduce

1. Cast a spell in the overworld.
2. Without reloading the world, go to the nether and cast the same spell.
3. Reload the world and attempt casting in both dimensions.

### Iron's Spells N Spellbooks version

1.0.5

### Forge version

1.19.2 - 43.2.8

**Comment by iron431** [comment] 2023-05-03 17:20
I am unable to reproduce this issue. Were you using any other mods at the time? If so, please edit your post to include them plus any logs/other information.

**Comment by iron431** [comment] 2023-05-06 04:44
@Jackiecrazy Is this still happening? With no other response/information, I'm going to close this issue.

**Comment by LILPRINCES** [comment] 2023-05-06 07:06
> 这还在发生吗？没有其他响应/信息，我将关闭此问题。
It seems that this bug only occurs in a server game.

**Comment by lab3** [comment] 2023-05-06 14:19
We have not been able to replicate this in dedicated server.  Can you please post your latest.log, debug.log and list of additional mods in use? @LILPRINCES, @Jackiecrazy

**Comment by chunye-shanhui** [comment] 2023-05-07 06:47
All I have to do to teleport to another dimension will cause the magic to be unrecoverable.

**Comment by lab3** [comment] 2023-05-07 16:13
@LILPRINCES @Jackiecrazy It looks like this might be related to a conflict with the "Blue Skies" mod Issue #26 .  Are you both using that as well?  If not please post your mod lists and upload your latest.log and debug.log in a gist https://gist.github.com/

**Closed as completed** 2023-05-07 19:03 UTC
Labels: bug, needs info

**Comment by chunye-shanhui** [comment] 2023-05-08 01:16
Yes, I was the one who raised issue #26, but I'm not sure about his problem.

**Comment by Jackiecrazy** [comment] 2023-05-10 00:04
I am indeed using Blue Skies.
