### ISSUE TITLE
[Bug] Conflict with Dimensional-Threading-Reforged mod

### ISSUE THREAD

**Issue by exdj158** [iron431/Irons-Spells-n-Spellbooks#10] opened 2023-05-01 18:04 UTC
### Observed behaviour

when installed Dimensional-Threading-Reforged,mana won't recover

### Expected behaviour

mana should auto recover

### Steps to reproduce

install Dimensional-Threading-Reforged mod

### Iron's Spells N Spellbooks version

1.0.1

### Forge version

1.19.2-43.2.8

**Comment by lab3** [comment] 2023-05-01 23:31
I was able to reproduce this.

**Comment by lab3** [comment] 2023-05-02 00:16
The issue is that TickEvent.LevelTickEvent event is not fired when "gamerule dimthread_active" is set to true.  Soon as you set it to false mana starts to regen again.  I'm not familar enough with Dimensional-Threading-Reforged to know what is going on yet.

**Comment by lab3** [comment] 2023-05-02 01:04
@exdj158 I did some digging and it looks like a bug in DimensionalThreading where they are not firing forge specific events. I'm guessing this is a leftover from them porting that mod from Fabric -> Forge.  Here is a link to the issue in their repo where I elaborate on what I found

https://github.com/CCr4ft3r/DimensionalThreading-Reforged/issues/6

**Comment by exdj158** [comment] 2023-05-02 02:12
Thanks for the validation, I've given up using Dimensional-Threading-Reforged now

**Comment by lab3** [comment] 2023-05-02 02:42
No problem. Closing this issue

**Closed as completed by lab3** 2023-05-02 02:42 UTC
Labels: bug

**Comment by lab3** [comment] 2023-05-15 04:05
@exdj158 They ended up fixing the issue

https://github.com/CCr4ft3r/DimensionalThreading-Reforged/issues/6
