### ISSUE TITLE
[Bug] heartstop and immediately fast

### ISSUE THREAD

**Issue by CorneredCube** [iron431/Irons-Spells-n-Spellbooks#196] opened 2023-10-29 19:47 UTC
### Observed behaviour

Whenver i use the heartstop spell it basically blinds me.

### Expected behaviour

I think its supposed to have a GUI that's transparent and have a cool effect but it completely adheres vision and is not transparent at all.

### Steps to reproduce

Just use the heartstop spell as a scroll

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-1.2.1

### Forge version

43.2.21

### Other mods

[modlist.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13199463/modlist.txt)
![KingSMP 1 19 2 10_29_2023 4_11_15 PM](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/111895072/25b73736-ca32-4721-b321-7e97f65e6664)

**Comment by iron431** [comment] 2023-10-29 20:46
include a screenshot and a modlist. this can do it automatically: https://legacy.curseforge.com/minecraft/mc-mods/modlist

**Comment by iron431** [comment] 2024-02-29 15:50
closing for duplicate of #231

**Closed as completed by iron431** 2024-02-29 15:50 UTC
Labels: triage
