### ISSUE TITLE
[Bug] Can't cast the long casting time spells.

### ISSUE THREAD

**Issue by Niconoko** [iron431/Irons-Spells-n-Spellbooks#116] opened 2023-07-26 01:36 UTC
### Observed behaviour

Seem to happen only to the spell that have long time casting and holding to shoot.

### Expected behaviour

It should shoot the spell, but instead it stopped abruptly.

### Steps to reproduce

1. Select spell book.
2. Select a spell.
3. Right click or hold to use spell.
4. Spell casting for a bit and it stopped.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.1.8

### Forge version

1.20.1-47.1.42

### Other mods

https://pastebin.com/Y6ZMAmR9

**Comment by iron431** [comment] 2023-07-26 02:47
Does this happen with continuous cast spells, such as Dragon Breath, and does this happen with vanilla's bow?

**Comment by Niconoko** [comment] 2023-07-26 21:56
Now that ye mentioned, with vanilla bow, sometimes, player's arms will aim sideway, but still shoot straight where crosshair aim. And yes, dragonbreath seem to have a short breath, like hiccup or sneeze.

**Comment by Niconoko** [comment] 2023-07-30 22:04
![IRSPL](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/24541618/f488aabb-3e44-42b1-8387-a7ae95263d64)
This is updated to version 1.2.0, mc 1.20.1, and it still do that.

**Comment by iron431** [comment] 2023-07-30 22:06
I have been unable to reproduce this issue. It may be related to the ping of the server. Does clicking to cast work?

**Comment by Niconoko** [comment] 2023-07-31 04:16
The spell that just click to shoot still work normally, just only those that having casting time and holding.

**Comment by Niconoko** [comment] 2023-08-04 09:13
Okay, just to let ye know, it only happen on server, in singleplayer is fine. (version 1.2.0)

**Comment by Niconoko** [comment] 2023-08-06 22:04
Here's the update, seem like using spell with mouse click or hold spell with holding mouse click doesn't work, but clicking the key on the keybind settings does work. Like ex, set a spell on slot 1 with Q button.

**Comment by lokilok1126** [comment] 2023-08-23 00:22
Is there a fix found for this yet?

**Comment by icpacilol725** [comment] 2023-09-12 09:10
Encounter same bug here. 1.19.2 1.2.1 - Moded server

Here's something im able to find out

**1. Change keybind to random keyboard can somewhat perform long casting spells**. But clicking doesnt work, holding it will make the spell repeatedly cast and cancel then eventually after few seconds of holding, releasing the button will cause the spell to perform normally

**2. Sometimes RMB can do the same thing like what the keyboard does, sometimes tho**. Maybe this can be trigger after changing back the keybind?

**3. Putting the spell in a book and using the same trick doesnt seem to work since once casted, the spell goes in cd**

**4. RMB a spell then esc (go to menu) will perform the spell normally**. RMB a spell then immediately go to menu, waiting for the whole casting time will do it :/. Cant quit mid cast

Hope this helpful :(

**Comment by Yuuzinhozi** [comment] 2023-09-17 04:39
Same here 1.19.2, (host server) Spell that have long time casting, or need holding for continue shooting is cancelling.

Work's better if i put some letter in the ''Quick Cast Slot'', but if i tried use a scroll, or use the mouse, will cancel, and rarely will really works.

**Comment by iron431** [comment] 2023-10-01 17:19
this should be fixed in v2.0.0

**Closed as completed by iron431** 2023-10-01 17:19 UTC
Labels: needs info

**Comment by icpacilol725** [comment] 2023-10-10 09:08
Hey iron431,

Thanks so much for the 2.0 update!

But the same issue seems to occur with spells that have cast duration as well
(For example: Dragon's breath, Blaze storm)

Is it fine if u make the same change with the previous problem with this one?
