### ISSUE TITLE
[Bug] [1.20.1] Pyromancer Trader crashes Client

### ISSUE THREAD

**Issue by finlader** [iron431/Irons-Spells-n-Spellbooks#638] opened 2024-10-22 19:24 UTC
### Observed behaviour

When going to trade with the Pyromancer, the entire game freezes, and then crashes. 

### Expected behaviour

Trading with the Pyromancer opens a trade window.

### Steps to reproduce

1. Find a Pyromancer trader
2. Try to right-click on them and trade
3. Game freezes and crashes

### Server Type

Single Player

### Crashlog

https://gist.github.com/finlader/f106a61677a2c725dcd962f99d96e17f

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.3

### Forge version

47.3.0

### Other mods

Listed in Crash Report

**Comment by iron431** [comment] 2024-10-22 19:33
closing for duplicate of #634

**Closed as completed by iron431** 2024-10-22 19:33 UTC
Labels: duplicate
