### ISSUE TITLE
[Bug] Crash on 1.19.2

### ISSUE THREAD

**Issue by woodgoldtwo** [iron431/Irons-Spells-n-Spellbooks#91] opened 2023-07-11 16:47 UTC
### Observed behaviour

The game seems to randomly crash when a priest casts a spell but i don't know if that is actually the cause or if something else is causing the game to crash

### Expected behaviour

The game shouldn't crash

### Steps to reproduce

I have no idea how to reproduce this since i don't know what caused it in the first place

### Server Type

Single Player

### Crashlog

https://gist.github.com/Woodgoldtwo/64d5189b9e715382104a8d7991700d5e

### Iron's Spells N Spellbooks version

1.19.2-1.1.7

### Forge version

1.19.2 - 43.2.14

### Other mods

They are listed at the bottom of the crash-log

**Comment by woodgoldtwo** [comment] 2023-07-11 16:48
Sorry for the general lack of information in this issue but i don't know exactly what happened so i can't provide any detailed information

**Comment by woodgoldtwo** [comment] 2023-07-11 16:49
why did it close?

(edit: i accidentally pressed the "close with comment" button thinking that it was enabled by default and that pressing it would make it not close the issue)

**Comment by iron431** [comment] 2023-07-16 18:23
![](https://github.trello.services/images/mini-trello-icon.png) [something is fucked up with entities](https://trello.com/c/JwEM6NO8/675-something-is-fucked-up-with-entities)

**Comment by iron431** [comment] 2023-07-16 18:25
looks like a duplicate of #85

**Closed as completed** 2023-07-17 01:54 UTC
Labels: bug, duplicate
