### ISSUE TITLE
[Bug-1.20.1] Crash when using multipart spells.

### ISSUE THREAD

**Issue by Gbergz** [iron431/Irons-Spells-n-Spellbooks#102] opened 2023-07-16 09:54 UTC
### Observed behaviour

Using certain spells found in loot chests found around the world crashes the server. Maybe game if on Singleplayer.

### Expected behaviour

No crashes using the spell.s

### Steps to reproduce

1. Find a spell.
2. Use it.
3. Crash
Profit.

### Server Type

Dedicated Server

### Crashlog

https://gist.githubusercontent.com/Gbergz/ece4f2a64de1037d5741f413f0ae9628/raw/708a86eaf413bb5d362feb487cb5b61e838a440b/gistfile1.txt

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.7.jar

### Forge version

47.1.12

### Other mods

a modpack so there's a few.
https://gist.github.com/Gbergz/6a55ed1e24851224c632bfccf51d2e7e

**Comment by iron431** [comment] 2023-07-18 18:10
duplicate of #107 
update forge to 47.1.24 or higher to fix

**Closed as completed by iron431** 2023-07-18 18:10 UTC
Labels: bug, duplicate
