### ISSUE TITLE
[Bug] Dying too ice spells causes permant freezing

### ISSUE THREAD

**Issue by Kuggle01** [iron431/Irons-Spells-n-Spellbooks#36] opened 2023-05-15 03:18 UTC
### Observed behaviour

A necromancer Killed me with an ice spell and now I am forever frozen

### Expected behaviour

Too not be frozen after I respond

### Steps to reproduce

Get a necromancer too kill you with an ice spell, or kill yourself using ice spells some other way

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.0.9

### Forge version

1.19.2 - 43.2.11

### Other mods

Way too many too count, it's a modpack of like 250 mods

**Comment by lab3** [comment] 2023-05-15 14:47
@Kuggle01 we are having trouble replicating this. Anything in your modpack also deal with freeze?  Also, if you upload your latest.log and debug.log we can see if that sheds any light on it

**Comment by iron431** [comment] 2023-05-18 20:28
Still can't reproduce this. Without any further information, we will shortly close the issue.

**Closed as completed** 2023-06-06 16:23 UTC
Labels: bug
