### ISSUE TITLE
[Bug] Jei ArcaneAnvilRecipe hogging memory in a large modpack

### ISSUE THREAD

**Issue by ColdTearsYY** [iron431/Irons-Spells-n-Spellbooks#343] opened 2024-03-10 15:38 UTC
### Observed behaviour

![20240310232302](https://github.com/iron431/irons-spells-n-spellbooks/assets/65808439/362fd927-4dc8-481b-ad52-b57fa80905ae)
![20240310232314](https://github.com/iron431/irons-spells-n-spellbooks/assets/65808439/346ef2dc-2d5a-45dd-b544-9d0a8f57525d)
When there are many weapons could be used in arcane anvils to combine with scrolls, it lags when looking up in emi/jei to see the recipes in arcane anvil page. And it consumes a lot of memories.

### Expected behaviour

jei/emi is used smoothly when looking up recipes.

### Steps to reproduce

1.add jei, spellbooks and some mods to add weapons
2.open jei and choose "arcane anvil" page
3.stutter for a while and opened

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.0.1

### Forge version

1.20.1-47.2.20

**Comment by iron431** [comment] 2024-03-10 16:31
How does this memory usage compare to the normal anvil, which also creates a recipe for every weapon per enchantment type per level?

**Comment by iron431** [comment] 2024-03-10 17:40
@ColdTearsYY

**Comment by ColdTearsYY** [comment] 2024-03-11 02:42
other smithing recipes:
![20240311103409](https://github.com/iron431/irons-spells-n-spellbooks/assets/65808439/cbc9e11a-b4b7-43f5-9d0a-1a930283eb3b)
arcane anvil recipes:
![20240311103438](https://github.com/iron431/irons-spells-n-spellbooks/assets/65808439/5eb41da7-1fa9-4fdf-9709-b29c337886a4)

Without spellbook mod memory usage range:  from 3700 to 5500mb and gc
with mod: from 5900 to 7300mb and gc

**Comment by iron431** [comment] 2024-03-11 20:46
although not a leak, it is clearly hogging memory compared to other jei implementations. we'll look into why

**Comment by lab3** [comment] 2024-04-06 22:24
@ColdTearsYY I'm having trouble reproducing this.  Do you have some examples of mods that when added create this issue?

**Comment by ColdTearsYY** [comment] 2024-04-07 03:12
Download link: windmc.top:5244/mods.zip
This is my whole mods folder test above.
I have already removed emi mod and iron‘s spellbook mod due to the mentioned issue so you could download the file, add mods and test.
@lab3 thx a lot

**Comment by Sebedidep** [comment] 2024-04-22 18:46
@lab3 Hello, did you had some time to look into the problem? I have a similar Observation. 
Maybe Iron's spells 'n speelbooks together with apotheosis is blowing up the memory allocation?
hprof file is generated through spark.

only example to reproduce is the modpack im playing: 
https://www.curseforge.com/minecraft/modpacks/sebastian24443-creation

really great mod by the way :) 

![grafik](https://github.com/iron431/irons-spells-n-spellbooks/assets/154062108/14e1db83-117b-4b27-ae37-aafd7597bad9)

**Comment by dgtyPedro** [comment] 2024-04-23 12:51
Having the same problem trying to add Iron's Spells in Prominence II Classic.

Is there any way to disable the JEI recipe for the Arcane Anvil?

**Comment by Sebedidep** [comment] 2024-04-23 15:12
I know that you can manipulate recipes with KubeJS, but i didnt found anything about it on google to remove recipes from anvils.

**Comment by LegendaryTicket9** [comment] 2024-05-22 06:44
I have found the potential cause of the memory leak in the "Arcane Anvil View Recipes", it usually sits on the last page:
![memory leak](https://github.com/iron431/irons-spells-n-spellbooks/assets/157869221/bcc0649a-18ab-4f25-9226-7463a6302b50)

**Comment by Sebedidep** [comment] 2024-06-23 11:02
Yeah, this seems to be the problem. 3 months later and there seems to be no fix at all from the devs.
Using up to 25% of memory is not accetable.
Would be nice if there was a config option to completly disable the function to enchant weapons with scrolls.
For me the spellbooks are enough to use magic. I dont need weapons with magic spells. Yeah, would be nice to disable it.
(Or maybe an Whitelist or Blacklist option for specific mods to use this kind of feature.)

They are adding a recipe for the arcane anvil for every kind of scroll, for every lvl of this scroll (~700), for every possible weapon / armor.
If you just add Simply Swords (~160 Weapons) you would add ~112.000 anvil recipes.

And it get's worse for every update when they add another spell.

**Comment by iron431** [comment] 2024-06-23 22:20
> 3 months later and there seems to be no fix at all from the devs

Fix it yourself then. We have other things to do in life than play minecraft. We have a fix prepared in a branch but haven't gotten the time to test it yet.

**Comment by Sebedidep** [comment] 2024-06-24 07:49
Hello, I didn't mean to sound rude. I appreciate all your work guys, thanks for this!
This mod is one of the best magic mods in my opinion. 
I still have this mod installed and just deactivated JEI and use instead EMI. EMI does not have Anvil Recipe function without JEI.
If you guys have something in a branch and working on it, then this is a good message. 
Family and Work goes first and after that comes the hobby.

**Comment by iron431** [comment] 2024-07-05 23:33
fixed in 3.2.1

**Closed as completed by iron431** 2024-07-05 23:33 UTC
Labels: bug
