### ISSUE TITLE
[Bug] Spells HUD error (Mod incompatibility)

### ISSUE THREAD

**Issue by Crazy-Elipsis** [iron431/Irons-Spells-n-Spellbooks#190] opened 2023-10-21 03:40 UTC
### Observed behaviour

Having the FPS Monitor mod enabled makes the spell HUD solid instead of transparent. This causes the other spells being to be unseen, but you can only a spell once its selected.

As you can see, even the white cooldown bar is solid too.

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/148471848/51c59a37-de27-4f48-9343-1c82e4e84615)

### Expected behaviour

It should look like this.

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/148471848/e219b664-854d-41c2-9f93-3d76987ac66c)

### Steps to reproduce

Just have the mod on and boot up the game. That's it.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 2.0.1

### Forge version

47.1.3

### Other mods

**Mod:** https://www.curseforge.com/minecraft/mc-mods/fps-monitor

**Mod Description:** _FPS Monitor is a lightweight, configurable and versatile tool to display game information on screen for easy access and readability. The mod can display the clients FPS (Frames per second), server connection ping and memory usage both on screen as a HUD and in the game-window title bar. The mod is coded to both run on Forge & Fabric and will be supported for all version from 1.16 and above._

**Comment by Caelinus** [comment] 2023-10-21 19:09
This also occurs when using the mod ImmediatelyFast 1.2.6 (https://www.curseforge.com/minecraft/mc-mods/immediatelyfast) with Iron's Spells 2.0.1.

The observed behavior and expected behavior perform exactly the same as the above examples given by Crazy-Elipsis. 

I do not have time to do a thorough test, but I think it is likely due to the mods attempted optimizations to GUI rendering.

**Comment by iron431** [comment] 2024-02-29 15:40
closing for duplicate of #231

**Closed as completed by iron431** 2024-02-29 15:40 UTC
Labels: triage
