### ISSUE TITLE
[Bug] CTD with Project MMO when attempting to trade with Priest Villagers

### ISSUE THREAD

**Issue by malice936** [iron431/Irons-Spells-n-Spellbooks#353] opened 2024-03-16 18:32 UTC
### Observed behaviour

On first attempt at speaking with a Priest Villager from Iron's Spells 'n Spellbooks, the trade menu will open and the player can trade as normal, any subsequent attempt to interact in any way, including attacking causes the game to CTD.

### Expected behaviour

The ability to open a trade dialogue with the Priest more than once.

### Steps to reproduce

1. Open a trade dialogue with a Priest Villager.
2. Close the dialogue.
3. Attempt to open it again, or attempt to attack the villager.

### Server Type

Single Player

### Crashlog

https://gist.github.com/malice936/e2f4d6379a9a906f7cd356b72b843d9e

### Iron's Spells N Spellbooks version

1.20.1-3.0.1

### Forge version

1.20.1-47.2.0

### Other mods

caelus-forge-3.1.0+1.20
curios-forge-5.7.0+1.20.1
geckolib-forge-1.20.1-4.4.2
player-animation-lib-forge-1.0.2-rc1+1.20
pmmo-1.20.1-1.2.18

**Comment by iron431** [comment] 2024-03-16 19:01
It seems like PMMO is trying to generate the priest's trades from the client. we can just make the trade have a client fallback but this is a weird behavior on PMMO's end.

**Comment by malice936** [comment] 2024-03-16 23:25
Here is the response from Caltinor over there, it seems you both disagree on the source of the problem so I will just link you to the other post so you 2 can sort it out.

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/7574750/f2e4b808-799a-4171-8765-445d9939dfe2)
https://github.com/Caltinor/Project-MMO-2.0/issues/498

**Comment by iron431** [comment] 2024-03-17 00:46
there are no mixins involved with this

**Comment by Caltinor** [comment] 2024-03-17 11:21
What PMMO is doing in this scenario is serializing the entity's NBT and passing that through the check for whether the player can interact with that entity. The NBT is provided because players can use it when defining restrictions, such as requiring a player to have a certain skill level to interact with master level villagers or even if the villager has certain trades.

From what I can tell, [fcaea5a](https://github.com/iron431/irons-spells-n-spellbooks/commit/fcaea5af2be7123046abbe244126ba4d9b61ffbd) would have been the cause.  The `MerchantOffers` list was not null, but one of the `MerchantOffer` instances in the list of offers was.  That was causing the serialization to fail.  This commit *should* fix it.

**Comment by iron431** [comment] 2024-03-17 18:10
should be fixed in 3.1.0

**Closed as completed by iron431** 2024-03-17 18:10 UTC
Labels: incompatability
