### ISSUE TITLE
[Bug] Apotheosis missing elemental gems

### ISSUE THREAD

**Issue by Molioron** [iron431/Irons-Spells-n-Spellbooks#338] opened 2024-03-02 22:31 UTC
### Observed behaviour

The only gem related to this mod that seems to appear is spell resistance gem. other gems such as elemental power gems seem to not show as a valid preset

### Expected behaviour

more than 1 type of Iron's Spells N Spellbooks gem is available, more specifically elemental power gems.

### Steps to reproduce

1. run Iron's Spells N Spellbooks with apotheosis
2. do /apoth gem fromPreset
3. notice that for iron's spells, only "irons_spellbooks:spell_resist" is available

### Server Type

Single Player

### Crashlog

not a crashlog, but might be related: https://pastebin.com/9MJBFi92

### Iron's Spells N Spellbooks version

1.20.1-3.0.1

### Forge version

1.20.1-47.2.20

### Other mods

Apotheosis 1.20.1-7.3.1
Apotheotic_additions1.5

**Comment by iron431** [comment] 2024-03-02 22:38
closing for duplicate of #206

**Closed as completed by iron431** 2024-03-02 22:38 UTC
Labels: duplicate
