### ISSUE TITLE
[Bug] v3.8.1 crashes both client and server

### ISSUE THREAD

**Issue by darock830** [iron431/Irons-Spells-n-Spellbooks#632] opened 2024-10-22 06:36 UTC
### Observed behaviour

tried 3.8.1 to see if the load failure was fixed. Neither client nor server can launch still.
Here's server crashlog: https://pastebin.com/EWYhfbej
Here's client crashlog: https://pastebin.com/z40tJLcT

### Expected behaviour

expected the new update to work

### Steps to reproduce

1. install the latest mod version 3.8.1
2. crash

### Server Type

Dedicated Server

### Crashlog

https://pastebin.com/EWYhfbej

### Iron's Spells N Spellbooks version

v1.21-3.8.1

### Forge version

neoforge 21.1.72

**Comment by iron431** [comment] 2024-10-22 16:06
please stop reporting two issues at once. closing this for duplicate of server issue #633

**Closed as completed by iron431** 2024-10-22 16:06 UTC
Labels: duplicate
